[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gitignore-generator-cli"
version = "0.1.0"
dependencies = [
    "click",
    "requests",
]

[project.scripts]
ign = "gi_tool.main:generate"